### ISSUE TITLE
Make Guide translatable

### ISSUE THREAD

**Issue by adiee5** [Nokse22/tactics#15]
As of now, translators can't translate the in-program guide. It would be nice, if one could translate it

**Comment by Nokse22** [comment]
I didn't notice, I have taken the opportunity to improve it

**Comment by adiee5** [comment]
Thank you very much! Although there are few issues in the way the guide got handled, especially here: 

https://github.com/Nokse22/ultimate-tic-tac-toe/blob/3e6cdff6915b1e9788b004b6caf49e63816ceada/po/ultimate-tic-tac-toe.pot#L74
https://github.com/Nokse22/ultimate-tic-tac-toe/blob/3e6cdff6915b1e9788b004b6caf49e63816ceada/src/main.py#L73
https://github.com/Nokse22/ultimate-tic-tac-toe/blob/3e6cdff6915b1e9788b004b6caf49e63816ceada/src/main.py#L80

as we can see, POT decided to assign one translation to both instances. Some languages are more contextual than this, making the translation fall apart. my suggestion would be to just not be afraid of adding *some* formatting flags to POT thus make them less fragmented.

**Comment by adiee5** [comment]
To be fair, the *`any`* word seems to be the only problematic thing, else is fine as is

**Comment by adiee5** [comment]
I accidentally got arround the issue anyway, somehow

**Comment by Nokse22** [comment]
I can change the rules string so that the word `any` is not translated alone (so removing the italic tags around). It wouldn't be a problem.

**Comment by adiee5** [comment]
For some reason, guide doesn't get translated at all. As if pot doesn't affect the page...

**Comment by adiee5** [comment]
![obraz](https://github.com/user-attachments/assets/7e7f629e-55b7-4f6b-bd80-260e5a895aa6)
This shouldn't be in english after all of my changes

**Comment by Nokse22** [comment]
Try again after the last [commit](https://github.com/Nokse22/ultimate-tic-tac-toe/commit/945d462f649402ec927da239301ab6e082028d76), I had this issue in another app

**Comment by adiee5** [comment]
Ok, it works now!
