### ISSUE TITLE
Add executable permissions

### ISSUE THREAD

**Issue by Eloitor** [Nokse22/tactics#4]
Hi! I'm trying to package ultimate-tic-tac-toe for void linux.

I'm using meson, and after the build and the installation, I get `permission denied (EACCES).` when I attempt to run it.

If I add executable  permissions: `sudo chmod +x /usr/bin/ultimate-tic-tac-toe` it works as expected.

I think that this is something that can be changed within meson, but I'm not sure...

**Comment by Eloitor** [comment]
I see, an "x" is needed in https://github.com/Nokse22/ultimate-tic-tac-toe/blob/master/src/meson.build#L26

Should I open a PR?

**Comment by Nokse22** [comment]
Hello. Yes, you may open a PR.
